### ISSUE TITLE
config fold is not exist

### ISSUE THREAD

**Issue by tingxr** [echoanran/CIS#1]
。。。

**Comment by chen-yingjie** [comment]
Hi~The config path in run-cisnet.py is just a path for saving the generated yaml files, which could be set by yourself.

**Comment by tingxr** [comment]
Ok, thansk.&nbsp; But i have a another problem, that is, an error "no model named 'processor.show-info" during runing.



---Original---
From: "Yingjie ***@***.***&gt;
Date: Wed, Nov 16, 2022 20:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [echoanran/CIS] config fold is not exist (Issue #1)




 
Hi~The config path in run-cisnet.py is just a path for saving the generated yaml files, which could be set by yourself.

**Comment by chen-yingjie** [comment]
We've updated main.py to fix the problem. Thanks for your reminder!
